// Mock data for development without database

export const mockNews = [
  {
    id: '1',
    titleEn: 'MLA Announces New Development Projects',
    titleHi: 'विधायक ने नई विकास परियोजनाओं की घोषणा की',
    contentEn: 'In a significant announcement today, the MLA revealed plans for several new development projects aimed at improving infrastructure and public services in the constituency. The projects include road construction, water supply systems, and educational facilities.',
    contentHi: 'आज एक महत्वपूर्ण घोषणा में, विधायक ने निर्वाचन क्षेत्र में बुनियादी ढांचे और सार्वजनिक सेवाओं में सुधार के उद्देश्य से कई नई विकास परियोजनाओं की योजनाओं का खुलासा किया।',
    slug: 'mla-announces-new-development-projects',
    imageUrl: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=800&h=600&fit=crop',
    published: true,
    publishedAt: new Date('2024-01-15'),
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    titleEn: 'Healthcare Initiative Launched',
    titleHi: 'स्वास्थ्य देखभाल पहल शुरू की गई',
    contentEn: 'A new healthcare initiative has been launched to provide better medical facilities to rural areas. The program includes mobile health units and free health checkup camps.',
    contentHi: 'ग्रामीण क्षेत्रों में बेहतर चिकित्सा सुविधाएं प्रदान करने के लिए एक नई स्वास्थ्य देखभाल पहल शुरू की गई है।',
    slug: 'healthcare-initiative-launched',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=800&h=600&fit=crop',
    published: true,
    publishedAt: new Date('2024-01-10'),
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: '3',
    titleEn: 'Education Scholarship Program',
    titleHi: 'शिक्षा छात्रवृत्ति कार्यक्रम',
    contentEn: 'The MLA has announced a new scholarship program for meritorious students from economically weaker sections. The program aims to support higher education.',
    contentHi: 'विधायक ने आर्थिक रूप से कमजोर वर्ग के मेधावी छात्रों के लिए एक नया छात्रवृत्ति कार्यक्रम घोषित किया है।',
    slug: 'education-scholarship-program',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=600&fit=crop',
    published: true,
    publishedAt: new Date('2024-01-05'),
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: '4',
    titleEn: 'Infrastructure Development Update',
    titleHi: 'बुनियादी ढांचा विकास अपडेट',
    contentEn: 'Significant progress has been made on various infrastructure projects including road widening, bridge construction, and public facility improvements.',
    contentHi: 'सड़क चौड़ीकरण, पुल निर्माण और सार्वजनिक सुविधा सुधार सहित विभिन्न बुनियादी ढांचा परियोजनाओं पर महत्वपूर्ण प्रगति हुई है।',
    slug: 'infrastructure-development-update',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop',
    published: true,
    publishedAt: new Date('2024-01-01'),
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

export const mockPhotos = [
  {
    id: '1',
    titleEn: 'Public Meeting',
    titleHi: 'जनसभा',
    imageUrl: '/images/pic1.jpeg',
    category: 'Events',
    featured: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    titleEn: 'School Inauguration',
    titleHi: 'स्कूल का उद्घाटन',
    imageUrl: '/images/pic2.jpeg',
    category: 'Education',
    featured: true,
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: '3',
    titleEn: 'Road Construction',
    titleHi: 'सड़क निर्माण',
    imageUrl: '/images/pic3.jpeg',
    category: 'Infrastructure',
    featured: true,
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    id: '4',
    titleEn: 'Health Camp',
    titleHi: 'स्वास्थ्य शिविर',
    imageUrl: '/images/pic1.jpeg',
    category: 'Healthcare',
    featured: true,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: '5',
    titleEn: 'Village Visit',
    titleHi: 'गांव का दौरा',
    imageUrl: '/images/pic5.jpeg',
    category: 'Events',
    featured: true,
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    id: '6',
    titleEn: 'Community Meeting',
    titleHi: 'सामुदायिक बैठक',
    imageUrl: '/images/pic6.jpeg',
    category: 'Events',
    featured: false,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
]

export const mockVideos = [
  {
    id: '1',
    titleEn: 'MLA Addresses Public Gathering',
    titleHi: 'विधायक ने जनसभा को संबोधित किया',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&h=450&fit=crop',
    category: 'Speeches',
    featured: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    titleEn: 'Development Projects Overview',
    titleHi: 'विकास परियोजनाओं का अवलोकन',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=450&fit=crop',
    category: 'Projects',
    featured: true,
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: '3',
    titleEn: 'Education Initiative Launch',
    titleHi: 'शिक्षा पहल का शुभारंभ',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
    category: 'Education',
    featured: false,
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
  },
]

export const mockEvents = [
  {
    id: '1',
    titleEn: 'Public Meeting - Development Plans',
    titleHi: 'जनसभा - विकास योजनाएं',
    descriptionEn: 'Join us for a public meeting to discuss upcoming development plans and gather community feedback.',
    descriptionHi: 'आगामी विकास योजनाओं पर चर्चा करने और सामुदायिक प्रतिक्रिया एकत्र करने के लिए जनसभा में शामिल हों।',
    date: new Date('2024-02-15T10:00:00'),
    location: 'Community Hall, Main Street',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800',
    status: 'upcoming',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    titleEn: 'Health Camp - Free Checkup',
    titleHi: 'स्वास्थ्य शिविर - निःशुल्क जांच',
    descriptionEn: 'Free health checkup camp for all residents. Various health services will be available.',
    descriptionHi: 'सभी निवासियों के लिए निःशुल्क स्वास्थ्य जांच शिविर। विभिन्न स्वास्थ्य सेवाएं उपलब्ध होंगी।',
    date: new Date('2024-02-20T09:00:00'),
    location: 'Primary Health Center',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=800&h=600&fit=crop',
    status: 'upcoming',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: '3',
    titleEn: 'School Inauguration Ceremony',
    titleHi: 'स्कूल उद्घाटन समारोह',
    descriptionEn: 'Inauguration of the new primary school building with modern facilities.',
    descriptionHi: 'आधुनिक सुविधाओं के साथ नई प्राथमिक स्कूल इमारत का उद्घाटन।',
    date: new Date('2024-01-10T11:00:00'),
    location: 'New School Campus',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=600&fit=crop',
    status: 'past',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
]

export const mockAchievements = [
  {
    id: '1',
    titleEn: 'Best MLA Award',
    titleHi: 'सर्वश्रेष्ठ विधायक पुरस्कार',
    descriptionEn: 'Recognized for outstanding contribution to constituency development and public service.',
    descriptionHi: 'निर्वाचन क्षेत्र के विकास और सार्वजनिक सेवा में उत्कृष्ट योगदान के लिए मान्यता प्राप्त।',
    year: 2023,
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=600&h=600&fit=crop',
    category: 'Recognition',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    titleEn: '100% Road Connectivity',
    titleHi: '100% सड़क कनेक्टिविटी',
    descriptionEn: 'Achieved 100% road connectivity to all villages in the constituency.',
    descriptionHi: 'निर्वाचन क्षेत्र के सभी गांवों में 100% सड़क कनेक्टिविटी हासिल की।',
    year: 2023,
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600',
    category: 'Infrastructure',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    id: '3',
    titleEn: 'Education Excellence',
    titleHi: 'शिक्षा उत्कृष्टता',
    descriptionEn: 'Launched scholarship programs benefiting over 500 students.',
    descriptionHi: '500 से अधिक छात्रों को लाभान्वित करने वाले छात्रवृत्ति कार्यक्रम शुरू किए।',
    year: 2022,
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600',
    category: 'Education',
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    id: '4',
    titleEn: 'Healthcare Initiative',
    titleHi: 'स्वास्थ्य देखभाल पहल',
    descriptionEn: 'Established 5 new health centers in remote areas.',
    descriptionHi: 'दूरदराज के क्षेत्रों में 5 नए स्वास्थ्य केंद्र स्थापित किए।',
    year: 2022,
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=600',
    category: 'Healthcare',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: '5',
    titleEn: 'Water Supply Project',
    titleHi: 'जल आपूर्ति परियोजना',
    descriptionEn: 'Completed water supply project covering 50 villages.',
    descriptionHi: '50 गांवों को कवर करने वाली जल आपूर्ति परियोजना पूरी की।',
    year: 2021,
    imageUrl: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=600',
    category: 'Infrastructure',
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    id: '6',
    titleEn: 'Digital Literacy Program',
    titleHi: 'डिजिटल साक्षरता कार्यक्रम',
    descriptionEn: 'Trained 1000+ citizens in digital literacy and computer skills.',
    descriptionHi: '1000+ नागरिकों को डिजिटल साक्षरता और कंप्यूटर कौशल में प्रशिक्षित किया।',
    year: 2021,
    imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600&h=600&fit=crop',
    category: 'Education',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
]

// Helper function to simulate async database calls
export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))

